#!/bin/bash

# change domain
domain="domain.com"

liveDir="/etc/letsencrypt/live"
cert="${liveDir}/${domain}/cert.pem"
key="${liveDir}/${domain}/privkey.pem"

scriptUrl="https://github.com/ryecoaaron/scripts/raw/main/update_cert.sh"
scriptPath="/usr/sbin/update_cert.sh"

if [ ! -f "${scriptPath}" ]; then
  wget -O ${scriptPath} ${scriptUrl}
  chmod +x ${scriptPath}
fi

${scriptPath} "" ${cert} ${key} "letsencrypt"

exit 0
